# Generated by Django 4.1.5 on 2023-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='materialIcon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
