# Generated by Django 4.1.5 on 2023-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_materialicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='responsive_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
