# Generated by Django 4.1.5 on 2023-03-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_responsive_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='responsive_image',
            new_name='image2',
        ),
    ]
