# Generated by Django 4.1.5 on 2023-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='slogan',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
