# Generated by Django 4.1.5 on 2023-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_campaigns_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='slogan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
