# Generated by Django 4.1.5 on 2023-03-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Adet')),
                ('create_att', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sipariş Ürünleri',
                'db_table': 'Order_Items',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, null=True, verbose_name='Tamamlandı mı')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('first_name', models.CharField(max_length=10, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=10, verbose_name='Soyisim')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon No')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='İlçe')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Şehir')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Ülke')),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('adminnote', models.CharField(default='Beklemede', max_length=100)),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Siparişler',
                'db_table': 'Orders',
            },
        ),
    ]
